<?php

namespace Database\Seeders;

use App\Domains\Memora\Models\MemoraPricingTier;
use Illuminate\Database\Seeder;

class MemoraPricingTiersSeeder extends Seeder
{
    public function run(): void
    {
        $tiers = [
            [
                'slug' => 'starter',
                'name' => 'Starter',
                'description' => 'Perfect for getting started',
                'price_monthly_cents' => 0,
                'price_annual_cents' => 0,
                'storage_bytes' => 5 * 1024 * 1024 * 1024,
                'project_limit' => 1,
                'collection_limit' => 1,
                'selection_limit' => 1,
                'proofing_limit' => 1,
                'max_revisions' => 0,
                'watermark_limit' => 1,
                'preset_limit' => 0,
                'set_limit_per_phase' => 1,
                'team_seats' => 1,
                'raw_file_limit' => 1,
                'features' => ['selection', 'proofing', 'collection'],
                'features_display' => [
                    '1 Project',
                    '1 Collection',
                    '1 Selection (1 set)',
                    '1 Proofing (1 set)',
                    '1 Collection (1 set)',
                    '5GB Storage',
                    'Mazeloot branding',
                    'Community support',
                    'Homepage off',
                    '1 watermark',
                    'No presets',
                    'Brand Details, Domain, Brand Assets disabled',
                    'Social links disabled',
                    'Collection display disabled',
                    'Photo quality disabled',
                    'Legal documents disabled',
                ],
                'sort_order' => 1,
                'is_popular' => false,
            ],
            [
                'slug' => 'pro',
                'name' => 'Pro',
                'description' => 'For solo photographers with regular clients',
                'price_monthly_cents' => 1500,
                'price_annual_cents' => 14400,
                'storage_bytes' => 100 * 1024 * 1024 * 1024,
                'project_limit' => null,
                'collection_limit' => null,
                'selection_limit' => null,
                'proofing_limit' => null,
                'max_revisions' => 5,
                'watermark_limit' => 3,
                'preset_limit' => 5,
                'set_limit_per_phase' => null,
                'team_seats' => 1,
                'raw_file_limit' => 0,
                'features' => ['selection', 'proofing', 'collection', 'custom_domain', 'remove_branding'],
                'features_display' => [
                    'Everything in Starter',
                    'Homepage on',
                    'Edit branding (Brand Details, Domain, Brand Assets)',
                    'Remove Mazeloot branding',
                    'Social links, Collection display, Photo quality, Legal documents',
                    '3 watermarks, 5 presets',
                    'Unlimited projects, collections, sets per phase',
                    '5 revisions',
                    '100GB Storage',
                    'Email support',
                ],
                'sort_order' => 2,
                'is_popular' => true,
            ],
            [
                'slug' => 'studio',
                'name' => 'Studio',
                'description' => 'For growing photographers and event specialists',
                'price_monthly_cents' => 3500,
                'price_annual_cents' => 33600,
                'storage_bytes' => 500 * 1024 * 1024 * 1024,
                'project_limit' => null,
                'collection_limit' => null,
                'selection_limit' => null,
                'proofing_limit' => null,
                'max_revisions' => 10,
                'watermark_limit' => null,
                'preset_limit' => null,
                'set_limit_per_phase' => null,
                'team_seats' => 1,
                'raw_file_limit' => null,
                'features' => ['selection', 'proofing', 'collection', 'raw_files', 'custom_domain', 'remove_branding', 'advanced_analytics'],
                'features_display' => [
                    'Everything in Pro',
                    'Raw Files phase',
                    '10 revisions',
                    'Unlimited watermarks & presets',
                    '500GB Storage',
                    'Advanced analytics',
                    'Priority support',
                ],
                'sort_order' => 3,
                'is_popular' => false,
            ],
            [
                'slug' => 'business',
                'name' => 'Business',
                'description' => 'For studios and high-volume operations',
                'price_monthly_cents' => 5900,
                'price_annual_cents' => 58800,
                'storage_bytes' => null,
                'project_limit' => null,
                'collection_limit' => null,
                'selection_limit' => null,
                'proofing_limit' => null,
                'max_revisions' => 20,
                'watermark_limit' => null,
                'preset_limit' => null,
                'set_limit_per_phase' => null,
                'team_seats' => 5,
                'raw_file_limit' => null,
                'features' => ['selection', 'proofing', 'collection', 'raw_files', 'custom_domain', 'remove_branding', 'advanced_analytics', 'team', 'white_label', 'api'],
                'features_display' => [
                    'Everything in Studio',
                    'Team (5 seats)',
                    'White-label, API',
                    '20 revisions',
                    'Unlimited Storage',
                    '24/7 support',
                ],
                'sort_order' => 4,
                'is_popular' => false,
            ],
        ];

        foreach ($tiers as $tier) {
            MemoraPricingTier::updateOrCreate(
                ['slug' => $tier['slug']],
                $tier
            );
        }
    }
}
